# Generated by Django 5.2.9 on 2026-02-21 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='experienceprofessionnelle',
            new_name='users_exper_profil__e9d610_idx',
            old_name='experience__profil__d46ea6_idx',
        ),
        migrations.RenameIndex(
            model_name='experienceprofessionnelle',
            new_name='users_exper_est_pos_97b0af_idx',
            old_name='experience__est_pos_6f47af_idx',
        ),
        migrations.AlterModelTable(
            name='experienceprofessionnelle',
            table='users_experience_professionnelle',
        ),
        migrations.AlterModelTable(
            name='lienreseausocialprofil',
            table='users_lien_reseau_social_profil',
        ),
        migrations.AlterModelTable(
            name='profil',
            table='users_profiles',
        ),
    ]
