# Generated by Django 5.2.9 on 2026-01-21 20:27

import core.models
import core.utils.encoder
import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneePromotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('annee', models.SmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)], verbose_name='Année')),
                ('libelle', models.CharField(help_text='Ex: Promotion 2020, Promo 2020, etc.', max_length=50, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, help_text='Informations supplémentaires sur cette promotion', null=True, verbose_name='Description')),
                ('est_active', models.BooleanField(default=True, help_text='Permet de désactiver temporairement une année', verbose_name='Active')),
                ('ordre_affichage', models.IntegerField(default=0, help_text='Plus petit = affiché en premier', verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Année de promotion',
                'verbose_name_plural': 'Années de promotion',
                'db_table': 'annee_promotion',
                'ordering': ['-annee'],
            },
        ),
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('code', models.CharField(help_text='Code ISO 4217: XAF, EUR, USD', max_length=10, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('symbole', models.CharField(help_text='FCFA, €, $', max_length=10, verbose_name='Symbole')),
                ('taux_change_usd', models.DecimalField(blank=True, decimal_places=6, help_text='1 USD = X devise (mis à jour régulièrement)', max_digits=15, null=True, verbose_name='Taux de change USD')),
                ('date_mise_a_jour_taux', models.DateTimeField(blank=True, null=True, verbose_name='Date mise à jour du taux')),
                ('est_active', models.BooleanField(default=True, verbose_name='Active')),
                ('ordre_affichage', models.IntegerField(default=0, help_text='XAF en premier pour le Cameroun', verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Devise',
                'verbose_name_plural': 'Devises',
                'db_table': 'devise',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('nom', models.CharField(help_text='Nom complet du domaine', max_length=150, unique=True, verbose_name='Nom')),
                ('code', models.CharField(help_text='Code court: GCI, GIM, GEL, etc.', max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, help_text='Présentation du domaine, débouchés, compétences', null=True, verbose_name='Description')),
                ('categorie', models.CharField(blank=True, help_text='Ex: Génie, Santé, Sciences Sociales', max_length=50, null=True, verbose_name='Catégorie')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre_affichage', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Domaine',
                'verbose_name_plural': 'Domaines',
                'db_table': 'domaine',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ReseauSocial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('nom', models.CharField(help_text='LinkedIn, Facebook, GitHub, etc.', max_length=50, unique=True, verbose_name='Nom')),
                ('code', models.CharField(help_text='linkedin, facebook, github (minuscules, sans espaces)', max_length=20, unique=True, verbose_name='Code')),
                ('url_base', models.URLField(help_text='https://linkedin.com/in/, https://github.com/', verbose_name='URL de base')),
                ('type_reseau', models.CharField(choices=[('professionnel', 'Professionnel'), ('social', 'Social'), ('academique', 'Académique'), ('technique', 'Technique'), ('portfolio', 'Portfolio')], max_length=20, verbose_name='Type de réseau')),
                ('pattern_validation', models.CharField(blank=True, help_text="Expression régulière pour valider l'URL", max_length=255, null=True, verbose_name='Pattern de validation')),
                ('placeholder_exemple', models.CharField(blank=True, help_text='Ex: votre-nom ou username', max_length=255, null=True, verbose_name='Exemple de placeholder')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre_affichage', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Réseau social',
                'verbose_name_plural': 'Réseaux sociaux',
                'db_table': 'reseau_social',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='TitreHonorifique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('titre', models.CharField(help_text='Abréviation: Dr., Prof., Ing.', max_length=20, unique=True, verbose_name='Titre')),
                ('nom_complet', models.CharField(help_text='Docteur, Professeur, Ingénieur', max_length=100, verbose_name='Nom complet')),
                ('type_titre', models.CharField(choices=[('academique', 'Académique'), ('professionnel', 'Professionnel'), ('honorifique', 'Honorifique'), ('civilite', 'Civilité')], max_length=20, verbose_name='Type de titre')),
                ('description', models.TextField(blank=True, help_text="Explication du titre, conditions d'obtention", null=True, verbose_name='Description')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre_affichage', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Titre honorifique',
                'verbose_name_plural': 'Titres honorifiques',
                'db_table': 'titre_honorifique',
                'ordering': ['ordre_affichage', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Adresse email')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Numéro de téléphone')),
                ('mot_de_passe', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('role_systeme', models.CharField(choices=[('user', 'Utilisateur'), ('admin_site', 'Administrateur site'), ('super_admin', 'Super Administrateur')], default='user', max_length=20, verbose_name='Rôle système')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Accès admin Django')),
                ('groups', models.ManyToManyField(blank=True, related_name='ensp_user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='ensp_user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('ACCESS_DENIED', 'Access denied')], db_index=True, max_length=20, verbose_name='Action')),
                ('entity_type', models.CharField(db_index=True, max_length=100, verbose_name="Type d'entité")),
                ('entity_id', models.UUIDField(db_index=True, verbose_name="ID de l'entité")),
                ('old_values', models.JSONField(blank=True, encoder=core.utils.encoder.CountriesEncoder, null=True, verbose_name='Anciennes valeurs')),
                ('new_values', models.JSONField(blank=True, encoder=core.utils.encoder.CountriesEncoder, null=True, verbose_name='Nouvelles valeurs')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User agent')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecteurActivite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('nom', models.CharField(max_length=150, unique=True, verbose_name='Nom du secteur')),
                ('code', models.CharField(help_text='Ex: TECH, BTP, SANTE, FINANCE', max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('icone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icône')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre_affichage', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('categorie_parent', models.ForeignKey(blank=True, help_text='Permet une hiérarchie: Technologie > Informatique > IA', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_secteurs', to='core.secteuractivite', verbose_name='Secteur parent')),
            ],
            options={
                'verbose_name': "Secteur d'activité",
                'verbose_name_plural': "Secteurs d'activité",
                'db_table': 'secteur_activite',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom de la filière')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('niveau', models.CharField(choices=[('licence', 'Licence'), ('ingenieur', 'Ingénieur'), ('master', 'Master'), ('doctorat', 'Doctorat'), ('autre', 'Autre')], max_length=50, verbose_name='Niveau')),
                ('duree_annees', models.SmallIntegerField(blank=True, null=True, verbose_name='Durée (années)')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Active')),
                ('ordre_affichage', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='core.domaine', verbose_name='Domaine')),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'db_table': 'filiere',
                'ordering': ['domaine', 'ordre_affichage', 'nom'],
                'unique_together': {('domaine', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('token', models.CharField(max_length=6, unique=True, verbose_name='Token')),
                ('expires_at', models.DateTimeField(default=core.models.get_password_reset_token_expiry, verbose_name="Date d'expiration")),
                ('is_used', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Token de réinitialisation de mot de passe',
                'verbose_name_plural': 'Tokens de réinitialisation de mot de passe',
                'db_table': 'password_reset_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='password_re_token_060a1f_idx'), models.Index(fields=['expires_at'], name='password_re_expires_8e96b7_idx')],
            },
        ),
    ]
