# Generated by Django 5.2.9 on 2026-02-21 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='core_passwo_token_ed8c87_idx',
            old_name='password_re_token_060a1f_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='core_passwo_expires_cbadab_idx',
            old_name='password_re_expires_8e96b7_idx',
        ),
        migrations.AlterModelTable(
            name='anneepromotion',
            table='cores_annee_promotions',
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table='core_audit_logs',
        ),
        migrations.AlterModelTable(
            name='devise',
            table='core_devises',
        ),
        migrations.AlterModelTable(
            name='domaine',
            table='core_domaines',
        ),
        migrations.AlterModelTable(
            name='filiere',
            table='core_filieres',
        ),
        migrations.AlterModelTable(
            name='passwordresettoken',
            table='core_password_reset_tokens',
        ),
        migrations.AlterModelTable(
            name='reseausocial',
            table='core_reseau_sociaux',
        ),
        migrations.AlterModelTable(
            name='secteuractivite',
            table='core_secteur_activites',
        ),
        migrations.AlterModelTable(
            name='titrehonorifique',
            table='core_titre_honorifiques',
        ),
        migrations.AlterModelTable(
            name='user',
            table='core_users',
        ),
    ]
