# Generated by Django 5.2.9 on 2026-03-06 12:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_rename_password_re_token_060a1f_idx_core_passwo_token_ed8c87_idx_and_more'),
        ('users', '0002_rename_experience__profil__d46ea6_idx_users_exper_profil__e9d610_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('source_object_id', models.UUIDField(blank=True, null=True, verbose_name='id de la source')),
                ('source_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='type de source (cache)')),
                ('category', models.CharField(choices=[('SYSTEM', 'Système'), ('CHAT', 'Chat'), ('NETWORK', 'Réseau'), ('OPPORTUNITY', 'Opportunité'), ('ADMIN', 'Administration')], default='SYSTEM', max_length=20, verbose_name='catégorie')),
                ('action_type', models.CharField(max_length=50, verbose_name="type d'action")),
                ('title', models.CharField(max_length=255, verbose_name='titre')),
                ('content', models.TextField(verbose_name='contenu')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='lien')),
                ('is_read', models.BooleanField(default=False, verbose_name='lu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lu le')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.profil', verbose_name='destinataire')),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype', verbose_name='type de source')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'db_table': 'core_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['destinataire', 'is_read', '-created_at'], name='core_notifi_destina_e5856b_idx'), models.Index(fields=['source_content_type', 'source_object_id'], name='core_notifi_source__fdf7df_idx')],
            },
        ),
    ]
