# Generated by Django 5.2.9 on 2026-02-11 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('network', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnementorganisation',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements_orgs', to='users.profil'),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_participants', to='network.conversation'),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_participations', to='users.profil'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='conversations', through='network.ConversationParticipant', to='users.profil', verbose_name='participants'),
        ),
        migrations.AddField(
            model_name='demandeaccesgroupe',
            name='demandeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_acces_groupes', to='users.profil', verbose_name='demandeur'),
        ),
        migrations.AddField(
            model_name='demandeaccesgroupe',
            name='traite_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to='users.profil', verbose_name='traité par'),
        ),
        migrations.AddField(
            model_name='demandementoring',
            name='domaines',
            field=models.ManyToManyField(blank=True, help_text='Domaines souhaités pour le mentorat', to='core.domaine'),
        ),
        migrations.AddField(
            model_name='demandementoring',
            name='filieres',
            field=models.ManyToManyField(blank=True, help_text='Filières souhaitées pour le mentorat', to='core.filiere'),
        ),
        migrations.AddField(
            model_name='demandementoring',
            name='mentee',
            field=models.ForeignKey(help_text='Étudiant qui demande le mentorat', on_delete=django.db.models.deletion.CASCADE, related_name='demandes_mentoring', to='users.profil'),
        ),
        migrations.AddField(
            model_name='feedbackmentorat',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_mentorat', to='users.profil'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='createur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes_crees', to='users.profil', verbose_name='créateur'),
        ),
        migrations.AddField(
            model_name='demandeaccesgroupe',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_acces', to='network.groupe', verbose_name='groupe'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='groupe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='network.groupe'),
        ),
        migrations.AddField(
            model_name='membregroupe',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='network.groupe', verbose_name='groupe'),
        ),
        migrations.AddField(
            model_name='membregroupe',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membre_groupes', to='users.profil', verbose_name='profil'),
        ),
        migrations.AddField(
            model_name='membreorganisation',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres_orgs', to='users.profil'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='domaines_expertise',
            field=models.ManyToManyField(help_text="Domaines dans lesquels j'ai de l'expérience", related_name='mentors', to='core.domaine'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='filieres_expertise',
            field=models.ManyToManyField(help_text='Filières dans lesquelles je peux mentorer', related_name='mentors', to='core.filiere'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='profil',
            field=models.OneToOneField(help_text='Alumni qui devient mentor', on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to='users.profil'),
        ),
        migrations.AddField(
            model_name='demandementoring',
            name='mentor_cible',
            field=models.ForeignKey(blank=True, help_text='Alumni ciblé spécifiquement (si demande directe)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_directes', to='network.mentorprofile'),
        ),
        migrations.AddField(
            model_name='demandementoring',
            name='mentor_repondant',
            field=models.ForeignKey(blank=True, help_text='Mentor qui a répondu à la demande', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to='network.mentorprofile'),
        ),
        migrations.AddField(
            model_name='demandementoring',
            name='mentors_notifies',
            field=models.ManyToManyField(blank=True, help_text='Mentors qui ont été notifiés de cette demande', related_name='demandes_recues', to='network.mentorprofile'),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='network.conversation', verbose_name='conversation'),
        ),
        migrations.AddField(
            model_name='message',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_edites', to='users.profil', verbose_name='édité par'),
        ),
        migrations.AddField(
            model_name='message',
            name='expediteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_envoyes', to='users.profil', verbose_name='expéditeur'),
        ),
        migrations.AddField(
            model_name='message',
            name='reponse_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses', to='network.message', verbose_name='réponse à'),
        ),
        migrations.AddField(
            model_name='messagemeta',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='network.message', verbose_name='message'),
        ),
        migrations.AddField(
            model_name='messagemeta',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_metas', to='users.profil', verbose_name='profil'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='secteur_activites',
            field=models.ManyToManyField(to='core.secteuractivite'),
        ),
        migrations.AddField(
            model_name='membreorganisation',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='network.organisation'),
        ),
        migrations.AddField(
            model_name='abonnementorganisation',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnes', to='network.organisation'),
        ),
        migrations.AddField(
            model_name='relationmentorat',
            name='demande_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relations_crees', to='network.demandementoring'),
        ),
        migrations.AddField(
            model_name='relationmentorat',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_mentorat', to='users.profil'),
        ),
        migrations.AddField(
            model_name='relationmentorat',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_actives', to='network.mentorprofile'),
        ),
        migrations.AddField(
            model_name='feedbackmentorat',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='network.relationmentorat'),
        ),
        migrations.AddField(
            model_name='sessionmentorat',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='network.relationmentorat'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationparticipant',
            unique_together={('conversation', 'profil')},
        ),
        migrations.AddIndex(
            model_name='groupe',
            index=models.Index(fields=['slug'], name='network_gro_slug_a0e02c_idx'),
        ),
        migrations.AddIndex(
            model_name='groupe',
            index=models.Index(fields=['type_acces'], name='network_gro_type_ac_cb32b6_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeaccesgroupe',
            index=models.Index(fields=['groupe', 'status'], name='network_dem_groupe__792bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeaccesgroupe',
            index=models.Index(fields=['demandeur', 'status'], name='network_dem_demande_4d4bba_idx'),
        ),
        migrations.AddIndex(
            model_name='membregroupe',
            index=models.Index(fields=['groupe', 'role'], name='network_mem_groupe__a41bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='demandementoring',
            index=models.Index(fields=['mentee', 'status'], name='network_dem_mentee__2ea516_idx'),
        ),
        migrations.AddIndex(
            model_name='demandementoring',
            index=models.Index(fields=['mentor_cible', 'status'], name='network_dem_mentor__758308_idx'),
        ),
        migrations.AddIndex(
            model_name='demandementoring',
            index=models.Index(fields=['status', 'created_at'], name='network_dem_status_a9f960_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-created_at'], name='network_mes_convers_c87299_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['client_id'], name='network_mes_client__e9111b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['type', 'conversation'], name='network_mes_type_f0ca98_idx'),
        ),
        migrations.AddIndex(
            model_name='messagemeta',
            index=models.Index(fields=['profil', 'date_lecture'], name='network_mes_profil__14126f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagemeta',
            unique_together={('message', 'profil')},
        ),
        migrations.AlterUniqueTogether(
            name='membreorganisation',
            unique_together={('profil', 'organisation')},
        ),
        migrations.AlterUniqueTogether(
            name='abonnementorganisation',
            unique_together={('profil', 'organisation')},
        ),
    ]
