# Generated by Django 5.2.9 on 2026-02-04 11:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='status',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='inactif', max_length=10, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='DemandeAccesGroupe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('refuse', 'Refusé')], default='en_attente', max_length=20, verbose_name='status')),
                ('message', models.TextField(blank=True, help_text='Message optionnel expliquant la demande', verbose_name='message de demande')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='date de traitement')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_acces_groupes', to='users.profil', verbose_name='demandeur')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_acces', to='network.groupe', verbose_name='groupe')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to='users.profil', verbose_name='traité par')),
            ],
            options={
                'verbose_name': "demande d'accès au groupe",
                'verbose_name_plural': "demandes d'accès aux groupes",
                'db_table': 'network_demande_acces_groupe',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['groupe', 'status'], name='network_dem_groupe__792bc4_idx'), models.Index(fields=['demandeur', 'status'], name='network_dem_demande_4d4bba_idx')],
                'unique_together': {('groupe', 'demandeur')},
            },
        ),
    ]
