# Generated by Django 5.2.9 on 2026-02-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media',
            field=models.FileField(null=True, upload_to='chat/media/%Y/%m/', verbose_name='média'),
        ),
        migrations.AlterField(
            model_name='message',
            name='media_name',
            field=models.CharField(max_length=255, null=True, verbose_name='nom média'),
        ),
        migrations.AlterField(
            model_name='message',
            name='media_size',
            field=models.PositiveIntegerField(null=True, verbose_name='taille média'),
        ),
        migrations.AlterField(
            model_name='message',
            name='media_type',
            field=models.CharField(max_length=100, null=True, verbose_name='type média'),
        ),
    ]
