# Generated by Django 5.2.9 on 2026-02-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_groupe_status_demandeaccesgroupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='est_ferme',
            field=models.BooleanField(default=False, verbose_name='fermé'),
        ),
    ]
