# Generated by Django 5.2.9 on 2026-02-06 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_groupe_est_ferme'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='demandeaccesgroupe',
            unique_together=set(),
        ),
    ]
