# Generated by Django 5.2.9 on 2026-02-21 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('network', '0003_alter_message_media_alter_message_media_name_and_more'),
        ('users', '0002_rename_experience__profil__d46ea6_idx_users_exper_profil__e9d610_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reponse_a',
        ),
        migrations.AddField(
            model_name='message',
            name='reference_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype', verbose_name='type de contenu'),
        ),
        migrations.AddField(
            model_name='message',
            name='reference_object_id',
            field=models.UUIDField(blank=True, null=True, verbose_name="l'id de la reference"),
        ),
        migrations.AddField(
            model_name='message',
            name='reference_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='type de reference (cache)'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['reference_content_type', 'reference_object_id'], name='network_mes_referen_5f1540_idx'),
        ),
    ]
