# Generated by Django 5.2.9 on 2026-02-06 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_demandeaccesgroupe_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membregroupe',
            unique_together=set(),
        ),
    ]
