# Generated by Django 5.2.9 on 2026-03-06 12:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_remove_message_reponse_a_and_more'),
        ('users', '0002_rename_experience__profil__d46ea6_idx_users_exper_profil__e9d610_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationmentorat',
            name='demande_origine',
        ),
        migrations.RemoveField(
            model_name='feedbackmentorat',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='feedbackmentorat',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='relationmentorat',
            name='mentee',
        ),
        migrations.RemoveField(
            model_name='relationmentorat',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='sessionmentorat',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='nombre_demandes_acceptees',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='nombre_max_mentees',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='nombre_mentees_actuels',
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='status',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20, verbose_name='statut'),
        ),
        migrations.CreateModel(
            name='MentorProfileValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('status_avant', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], max_length=20)),
                ('status_apres', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], max_length=20)),
                ('commentaire', models.TextField(blank=True, verbose_name='commentaire')),
                ('mentor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='network.mentorprofile', verbose_name='profil mentor')),
                ('valide_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_mentors_effectuees', to='users.profil', verbose_name='validé par')),
            ],
            options={
                'verbose_name': 'Validation de profil mentor',
                'verbose_name_plural': 'Validations de profils mentors',
                'db_table': 'network_mentor_profile_validation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='DemandeMentoring',
        ),
        migrations.DeleteModel(
            name='FeedbackMentorat',
        ),
        migrations.DeleteModel(
            name='RelationMentorat',
        ),
        migrations.DeleteModel(
            name='SessionMentorat',
        ),
    ]
