# Generated by Django 5.2.9 on 2026-03-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification'),
        ('network', '0005_remove_relationmentorat_demande_origine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='biographie',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='disponibilite',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Indisponible'), (25, 'Faible disponibilité'), (50, 'Disponibilité modérée'), (75, 'Très disponible'), (100, 'Disponibilité maximale')], default=50, help_text='Niveau de disponibilité pour le mentoring'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='domaines_expertise',
            field=models.ManyToManyField(related_name='mentors', to='core.domaine'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='filieres_expertise',
            field=models.ManyToManyField(related_name='mentors', to='core.filiere'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='status',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20),
        ),
    ]
