# Generated by Django 5.2.9 on 2026-02-08 23:51

import django.db.models.deletion
import network.models.chat
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0005_alter_membregroupe_unique_together"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "verbose_name": "conversation",
                "verbose_name_plural": "conversations",
                "db_table": "network_conversation",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "last_read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="dernière lecture"
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_participants",
                        to="network.conversation",
                    ),
                ),
                (
                    "profil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_participations",
                        to="users.profil",
                    ),
                ),
            ],
            options={
                "verbose_name": "participant à la conversation",
                "verbose_name_plural": "participants à la conversation",
                "db_table": "network_conversation_participant",
                "unique_together": {("conversation", "profil")},
            },
        ),
        migrations.AddField(
            model_name="conversation",
            name="participants",
            field=models.ManyToManyField(
                related_name="conversations",
                through="network.ConversationParticipant",
                to="users.profil",
                verbose_name="participants",
            ),
        ),
        migrations.CreateModel(
            name="MessageDM",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                ("contenu", models.TextField(verbose_name="contenu")),
                (
                    "piece_jointe",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="network/chat/files/",
                        validators=[
                            network.models.chat.validate_file_size,
                            network.models.chat.validate_file_extension,
                        ],
                        verbose_name="pièce jointe",
                    ),
                ),
                ("est_lu", models.BooleanField(default=False, verbose_name="lu")),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="network.conversation",
                        verbose_name="conversation",
                    ),
                ),
                (
                    "expediteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.profil",
                        verbose_name="expéditeur",
                    ),
                ),
            ],
            options={
                "verbose_name": "message DM",
                "verbose_name_plural": "messages DM",
                "db_table": "network_message_dm",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["conversation", "-created_at"],
                        name="network_mes_convers_7c8959_idx",
                    ),
                    models.Index(
                        fields=["expediteur", "-created_at"],
                        name="network_mes_expedit_ff65ee_idx",
                    ),
                ],
            },
        ),
    ]
