# Generated by Django 5.2.9 on 2026-02-09 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0006_conversation_conversationparticipant_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MessageDirect",
        ),
    ]
