# Generated by Django 5.2.9 on 2026-02-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_delete_messagedirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='membregroupe',
            name='derniere_lecture',
            field=models.DateTimeField(blank=True, help_text='Dernière date de lecture des messages du groupe', null=True, verbose_name='dernière lecture'),
        ),
        migrations.AddField(
            model_name='membregroupe',
            name='messages_non_lus',
            field=models.PositiveBigIntegerField(default=0, verbose_name='messages non lus'),
        ),
    ]
