# Generated by Django 6.0.2 on 2026-02-11 10:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0008_membregroupe_derniere_lecture_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "client_id",
                    models.UUIDField(blank=True, null=True, verbose_name="ID client"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("user", "Utilisateur"), ("system", "Système")],
                        default="user",
                        max_length=10,
                        verbose_name="type",
                    ),
                ),
                ("contenu", models.TextField(verbose_name="contenu")),
                (
                    "media",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="chat/media/%Y/%m/",
                        verbose_name="média",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="type média"
                    ),
                ),
                (
                    "media_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="nom média"
                    ),
                ),
                (
                    "media_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="taille média"
                    ),
                ),
                (
                    "edited_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date d'édition"
                    ),
                ),
            ],
            options={
                "verbose_name": "message",
                "verbose_name_plural": "messages",
                "db_table": "network_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageMeta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "date_lecture",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date de lecture"
                    ),
                ),
            ],
            options={
                "verbose_name": "métadonnée de message",
                "verbose_name_plural": "métadonnées de messages",
                "db_table": "network_message_meta",
            },
        ),
        migrations.RemoveIndex(
            model_name="messagedm",
            name="network_mes_convers_7c8959_idx",
        ),
        migrations.RemoveIndex(
            model_name="messagedm",
            name="network_mes_expedit_ff65ee_idx",
        ),
        migrations.RemoveIndex(
            model_name="messagegroupe",
            name="network_mes_groupe__4c282d_idx",
        ),
        migrations.RemoveIndex(
            model_name="messagegroupe",
            name="network_mes_groupe__c2a248_idx",
        ),
        migrations.RemoveIndex(
            model_name="messagegroupe",
            name="network_mes_expedit_0daac5_idx",
        ),
        migrations.AddField(
            model_name="conversation",
            name="groupe",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation",
                to="network.groupe",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="type",
            field=models.CharField(
                choices=[("dm", "Direct Message"), ("group", "Groupe")],
                default="dm",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="conversationparticipant",
            name="joined_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date d'ajout"
            ),
        ),
        migrations.AddField(
            model_name="conversationparticipant",
            name="messages_non_lus",
            field=models.PositiveIntegerField(
                default=0, verbose_name="messages non lus"
            ),
        ),
        migrations.AddField(
            model_name="conversationparticipant",
            name="role",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="rôle"
            ),
        ),
        migrations.AddField(
            model_name="membregroupe",
            name="premiere_visite_messages",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="première visite des messages"
            ),
        ),
        migrations.AlterField(
            model_name="membregroupe",
            name="messages_non_lus",
            field=models.PositiveIntegerField(
                default=0, verbose_name="messages non lus"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="network.conversation",
                verbose_name="conversation",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="edited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages_edites",
                to="users.profil",
                verbose_name="édité par",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="expediteur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages_envoyes",
                to="users.profil",
                verbose_name="expéditeur",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="reponse_a",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reponses",
                to="network.message",
                verbose_name="réponse à",
            ),
        ),
        migrations.AddField(
            model_name="messagemeta",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metas",
                to="network.message",
                verbose_name="message",
            ),
        ),
        migrations.AddField(
            model_name="messagemeta",
            name="profil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_metas",
                to="users.profil",
                verbose_name="profil",
            ),
        ),
        migrations.RemoveField(
            model_name="messagedm",
            name="conversation",
        ),
        migrations.RemoveField(
            model_name="messagedm",
            name="expediteur",
        ),
        migrations.RemoveField(
            model_name="messagegroupe",
            name="expediteur",
        ),
        migrations.RemoveField(
            model_name="messagegroupe",
            name="groupe",
        ),
        migrations.RemoveField(
            model_name="messagegroupe",
            name="reponse_a",
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "-created_at"],
                name="network_mes_convers_c87299_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["client_id"], name="network_mes_client__e9111b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["type", "conversation"], name="network_mes_type_f0ca98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagemeta",
            index=models.Index(
                fields=["profil", "date_lecture"], name="network_mes_profil__14126f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="messagemeta",
            unique_together={("message", "profil")},
        ),
        migrations.DeleteModel(
            name="MessageDM",
        ),
        migrations.DeleteModel(
            name="MessageGroupe",
        ),
    ]
