# Generated by Django 5.2.9 on 2026-01-21 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('organizations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnementorganisation',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='users.profil', verbose_name='Profil'),
        ),
        migrations.AddField(
            model_name='membreorganisation',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres_organisations', to='users.profil', verbose_name='Profil'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='secteur_activite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisations', to='core.secteuractivite', verbose_name="Secteur d'activité"),
        ),
        migrations.AddField(
            model_name='membreorganisation',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='organizations.organisation', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='abonnementorganisation',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnes', to='organizations.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterUniqueTogether(
            name='membreorganisation',
            unique_together={('profil', 'organisation', 'est_actif')},
        ),
        migrations.AlterUniqueTogether(
            name='abonnementorganisation',
            unique_together={('profil', 'organisation')},
        ),
    ]
