# Generated by Django 5.2.9 on 2026-01-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_remove_membreorganisation_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='site_web',
            field=models.URLField(blank=True, null=True, verbose_name='Site Web'),
        ),
    ]
