# Generated by Django 5.2.9 on 2026-01-17 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organisation_site_web'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='site_web',
        ),
    ]
