# Generated by Django 5.2.9 on 2026-01-21 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='createur_profil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes_crees', to='users.profil'),
        ),
        migrations.AddField(
            model_name='membregroupe',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='chat.groupe'),
        ),
        migrations.AddField(
            model_name='membregroupe',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profil'),
        ),
        migrations.AddField(
            model_name='message',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.groupe'),
        ),
        migrations.AddField(
            model_name='message',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profil'),
        ),
        migrations.AddField(
            model_name='validationgroupe',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='chat.groupe'),
        ),
        migrations.AddField(
            model_name='validationgroupe',
            name='validateur_profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profil'),
        ),
        migrations.AlterUniqueTogether(
            name='membregroupe',
            unique_together={('profil', 'groupe')},
        ),
    ]
