# Generated by Django 5.2.9 on 2026-01-28 01:06

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedScoreConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('profil_base_score', models.FloatField(default=1.0, help_text='Score de base pour les utilisateur')),
                ('profil_activity_coeff', models.FloatField(default=1.0, help_text="Coefficient les activites de l'utilisateur")),
                ('profil_report_penalty_per_report', models.FloatField(default=1.0, help_text="Penalite par signalement de l'utilisateur")),
                ('profil_report_threshold', models.IntegerField(default=10, help_text="Seuil de signalement de l'utilisateur")),
                ('post_base_score', models.FloatField(default=10.0, help_text='Score de base pour les posts')),
                ('post_penality_per_report', models.FloatField(default=10.0, help_text='Penalite par signalement de post')),
                ('post_report_threshold', models.IntegerField(default=10, help_text='Seuil de signalement de post')),
                ('time_decay_factor', models.FloatField(default=12.0, help_text='Facteur de diminution du score par temps')),
                ('boost_new_posts', models.BooleanField(default=True, help_text='Boost les nouveaux posts ')),
                ('new_posts_boost_factor', models.FloatField(default=2.0, help_text='Facteur de boost des nouveaux posts')),
                ('boost_new_posts_threshold', models.IntegerField(default=8, help_text='Duree de boost des nouveaux posts')),
                ('content_multipliers', models.JSONField(default=dict, help_text='JSON : {\n            "image": 2.0,\n            "video: 1.5,\n            "pooll: 1.2,\n            "link": 1.1,\n            "text": 1.0\n            "\n        }')),
                ('engagement_coefficients', models.JSONField(default=dict, help_text='JSON:{\n            comment: 3.0,\n            "like": 2.0,\n            "view: 0.1,\n            "share": 1.5\n        }')),
                ('is_active', models.BooleanField(default=False, help_text='Configuration actuellement utilisée')),
            ],
            options={
                'verbose_name': 'Configuration de score',
                'verbose_name_plural': 'Configurations des scores',
                'ordering': ['-is_active', 'updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('content', models.TextField(help_text='Contenu HTML du commentaire (rich-text)', verbose_name='Contenu')),
                ('content_text', models.TextField(blank=True, help_text='Version texte du contenu sans HTML', verbose_name='Contenu texte')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de likes')),
                ('replies_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de réponses')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.profil', verbose_name='Auteur')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='feeds.comment', verbose_name='Commentaire parent')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'db_table': 'feed_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('content', models.TextField(help_text='Contenu HTML du post (rich-text)', verbose_name='Contenu')),
                ('content_text', models.TextField(blank=True, help_text='Version texte du contenu sans HTML', verbose_name='Contenu texte')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('is_pinned', models.BooleanField(default=False, help_text='Post épinglé en haut du fil', verbose_name='Épinglé')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archivé')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de likes')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de commentaires')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('shares_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de partages')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='users.profil', verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'feed_post',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='feeds.comment', verbose_name='Commentaire')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='users.profil', verbose_name='Profil')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='feeds.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
                'db_table': 'feed_like',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feeds.post', verbose_name='Post'),
        ),
        migrations.CreateModel(
            name='PostScoreRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('calculated_score', models.FloatField()),
                ('calculation_time', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feeds.feedscoreconfig')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_records', to='feeds.post')),
            ],
            options={
                'verbose_name': 'Historique des poids des posts',
                'verbose_name_plural': 'Historique des poids des posts',
                'ordering': ['-calculation_time'],
            },
        ),
        migrations.CreateModel(
            name='ProfilScoreRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('calculated_score', models.FloatField()),
                ('calculation_time', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feeds.feedscoreconfig')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_records', to='users.profil')),
            ],
            options={
                'verbose_name': 'Historique des poids utilisateurs',
                'verbose_name_plural': 'Historique des poids utilisateurs',
                'ordering': ['-calculation_time'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harcèlement'), ('hate_speech', 'Discours haineux'), ('violence', 'Violence'), ('false_info', 'Fausse information'), ('inappropriate', 'Contenu inapproprié'), ('other', 'Autre')], max_length=50, verbose_name='Raison')),
                ('description', models.TextField(blank=True, help_text='Description détaillée du signalement', verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('reviewed', 'Examiné'), ('resolved', 'Résolu'), ('rejected', 'Rejeté')], default='pending', max_length=20, verbose_name='Statut')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'examen")),
                ('resolution_note', models.TextField(blank=True, verbose_name='Note de résolution')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='feeds.comment', verbose_name='Commentaire')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='feeds.post', verbose_name='Post')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to='users.profil', verbose_name='Rapporteur')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to='users.profil', verbose_name='Examiné par')),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'db_table': 'feed_report',
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('platform', models.CharField(blank=True, help_text='Plateforme de partage (linkedin, twitter, email, etc.)', max_length=50, null=True, verbose_name='Plateforme')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='feeds.post', verbose_name='Post')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_shares', to='users.profil', verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'Partage',
                'verbose_name_plural': 'Partages',
                'db_table': 'feed_share',
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('session_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Session key')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='feeds.post', verbose_name='Post')),
                ('profil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_views', to='users.profil', verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'Vue',
                'verbose_name_plural': 'Vues',
                'db_table': 'feed_view',
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='feed_post_created_e5d35a_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created_at'], name='feed_post_author__c854fa_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_pinned', '-created_at'], name='feed_post_is_pinn_28154d_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='feed_post_search__42b111_gin'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['post', 'created_at'], name='feed_like_post_id_e9cf16_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['comment', 'created_at'], name='feed_like_comment_9b52cc_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['profil', '-created_at'], name='feed_like_profil__91badc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('profil', 'comment'), ('profil', 'post')},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='feed_commen_post_id_3fe3f3_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', '-created_at'], name='feed_commen_author__bd8829_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent', 'created_at'], name='feed_commen_parent__273c50_idx'),
        ),
        migrations.AddIndex(
            model_name='postscorerecord',
            index=models.Index(fields=['post', '-calculation_time'], name='feeds_posts_post_id_61ea26_idx'),
        ),
        migrations.AddIndex(
            model_name='profilscorerecord',
            index=models.Index(fields=['profil', '-calculation_time'], name='feeds_profi_profil__bc0043_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-created_at'], name='feed_report_status_70601e_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['post', 'status'], name='feed_report_post_id_8a238d_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['comment', 'status'], name='feed_report_comment_129472_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('reporter', 'comment'), ('reporter', 'post')},
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['post', '-created_at'], name='feed_share_post_id_d1d178_idx'),
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['profil', '-created_at'], name='feed_share_profil__4f8d55_idx'),
        ),
        migrations.AddIndex(
            model_name='view',
            index=models.Index(fields=['post', '-created_at'], name='feed_view_post_id_931d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='view',
            index=models.Index(fields=['profil', '-created_at'], name='feed_view_profil__789c96_idx'),
        ),
    ]
