# Generated by Django 5.2.9 on 2026-02-11 18:47

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feeds', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.profil', verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='feeds.comment', verbose_name='Commentaire parent'),
        ),
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='feeds.comment', verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='like',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='users.profil', verbose_name='Profil'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='users.profil', verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='feeds.post', verbose_name='Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feeds.post', verbose_name='Post'),
        ),
        migrations.AddField(
            model_name='postscorerecord',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feeds.feedscoreconfig'),
        ),
        migrations.AddField(
            model_name='postscorerecord',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_records', to='feeds.post'),
        ),
        migrations.AddField(
            model_name='profilscorerecord',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feeds.feedscoreconfig'),
        ),
        migrations.AddField(
            model_name='profilscorerecord',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_records', to='users.profil'),
        ),
        migrations.AddField(
            model_name='report',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='feeds.comment', verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='report',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='feeds.post', verbose_name='Post'),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to='users.profil', verbose_name='Rapporteur'),
        ),
        migrations.AddField(
            model_name='report',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to='users.profil', verbose_name='Examiné par'),
        ),
        migrations.AddField(
            model_name='share',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='feeds.post', verbose_name='Post'),
        ),
        migrations.AddField(
            model_name='share',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_shares', to='users.profil', verbose_name='Profil'),
        ),
        migrations.AddField(
            model_name='view',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='feeds.post', verbose_name='Post'),
        ),
        migrations.AddField(
            model_name='view',
            name='profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_views', to='users.profil', verbose_name='Profil'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='feed_post_created_e5d35a_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created_at'], name='feed_post_author__c854fa_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_pinned', '-created_at'], name='feed_post_is_pinn_28154d_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='feed_post_search__42b111_gin'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['post', 'created_at'], name='feed_like_post_id_e9cf16_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['comment', 'created_at'], name='feed_like_comment_9b52cc_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['profil', '-created_at'], name='feed_like_profil__91badc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('profil', 'comment'), ('profil', 'post')},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='feed_commen_post_id_3fe3f3_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', '-created_at'], name='feed_commen_author__bd8829_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent', 'created_at'], name='feed_commen_parent__273c50_idx'),
        ),
        migrations.AddIndex(
            model_name='postscorerecord',
            index=models.Index(fields=['post', '-calculation_time'], name='feeds_posts_post_id_61ea26_idx'),
        ),
        migrations.AddIndex(
            model_name='profilscorerecord',
            index=models.Index(fields=['profil', '-calculation_time'], name='feeds_profi_profil__bc0043_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-created_at'], name='feed_report_status_70601e_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['post', 'status'], name='feed_report_post_id_8a238d_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['comment', 'status'], name='feed_report_comment_129472_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('reporter', 'comment'), ('reporter', 'post')},
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['post', '-created_at'], name='feed_share_post_id_d1d178_idx'),
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['profil', '-created_at'], name='feed_share_profil__4f8d55_idx'),
        ),
        migrations.AddIndex(
            model_name='view',
            index=models.Index(fields=['post', '-created_at'], name='feed_view_post_id_931d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='view',
            index=models.Index(fields=['profil', '-created_at'], name='feed_view_profil__789c96_idx'),
        ),
    ]
