"""
Django settings for enspm_hub project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import re
from pathlib import Path

import environ
from inertia.settings import settings as inertia_settings


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from a .env file
env = environ.Env()
env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG')

# 
MAINTENANCE_MODE = env.bool('MAINTENANCE_MODE', default=False) # type: ignore

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['*']) # type: ignore

# ==========================================
# CONFIGURATION EMAIL
# ==========================================

EMAIL_BACKEND = env.str('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend') # type: ignore

EMAIL_HOST = env.str('EMAIL_HOST', default='smtp.gmail.com') # type: ignore
EMAIL_PORT = env.int('EMAIL_PORT', default=587) # type: ignore
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True) # type: ignore
EMAIL_USE_SSL = env.bool('EMAIL_USE_SSL', default=True) # type: ignore
EMAIL_HOST_USER = env.str('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env.str('EMAIL_HOST_PASSWORD')

# resend for email sending in production environments like Render
RESEND_API_KEY = env.str('RESEND_API_KEY')

# Configuration des emails
DEFAULT_FROM_EMAIL = env.str('DEFAULT_FROM_EMAIL', default='noreply@enspmhub.com') # type: ignore
SERVER_EMAIL = env.str('SERVER_EMAIL', default='enspmhub@enspmhub.com') # type: ignore
SUPPORT_EMAIL = env.str('SUPPORT_EMAIL', default='enspmhub@enspmhub.com') # type: ignore
# Informations du site
SITE_NAME = env.str('SITE_NAME', default='ENSPM Hub') # type: ignore
SITE_URL = env.str('SITE_URL', default='http://localhost:8000') # type: ignore


# ==========================================
# CONFIGURATION HUEY (TASK QUEUE)
# ==========================================

# Configuration Huey avec SQLite (pour débuter)
HUEY = {
    'huey_class': 'huey.SqliteHuey',
    'name': 'enspm_hub_tasks',
    'filename': os.path.join(BASE_DIR, 'huey.db'),
    'results': True,
    'store_none': False,
    'immediate': False,  # False = mode asynchrone, True = mode synchrone (pour tests)
    'utc': True,
    'consumer': {
        'workers': env.int('HUEY_WORKERS', default=1), # type: ignore  # Nombre de workers pour traiter les tâches
        'worker_type': 'thread',  # 'thread', 'process' ou 'greenlet'
        'initial_delay': 0.1,
        'backoff': 1.15,
        'max_delay': 10.0,
        'scheduler_interval': 1,
        'periodic': True,  # Support des tâches périodiques
        'check_worker_health': True,
        'health_check_interval': 10,
    },
}

# Alternative : Configuration Huey avec Redis (pour production)
# Décommenter et installer redis-py: pip install redis
"""
HUEY = {
    'huey_class': 'huey.RedisHuey',
    'name': 'enspm_hub_tasks',
    'connection': {
        'host': 'localhost',
        'port': 6379,
        'db': 0,
        'max_connections': 20,
    },
    'immediate': False,
    'consumer': {
        'workers': 4,
        'worker_type': 'thread',
    },
}
"""


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "debug_toolbar",
    'huey.contrib.djhuey',
    "django_vite",
    "inertia",
    "ninja",
    'django_countries',
    
    "web",
    "core",
    "users",
    "organizations",
    "opportunities",
    "feeds",
    "chat",
    "stats",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "inertia.middleware.InertiaMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    'core.middleware.maintenance.MaintenanceMiddleware',
]

ROOT_URLCONF = 'enspm_hub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'enspm_hub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if 'DATABASE_URL' in env:
    DATABASES = {
        'default': env.db(),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# SÉCURITÉ & AUTHENTIFICATION
AUTH_USER_MODEL = 'core.User'
AUTHENTICATION_BACKENDS = [
    'core.backends.EmailOrPhoneAuthBackend',  # Notre backend personnalisé
    'django.contrib.auth.backends.ModelBackend', # Fallback au backend par défaut
]
from django.utils.timezone import timedelta
SIMPLE_JWT = {
   "USER_ID_CLAIM": "user_id",
   'ACCESS_TOKEN_LIFETIME': timedelta(days=90),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=180),
    'ROTATE_REFRESH_TOKENS': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': env('SECRET_KEY')
}
PASSWORD_RESET_TOKEN_DURATION = env.int('PASSWORD_RESET_TOKEN_DURATION', default=300)  # type: ignore # en secondes, par défaut 5 minutes
PASSWORD_RESET_TOKEN_DURATION = timedelta(seconds=PASSWORD_RESET_TOKEN_DURATION) # type: ignore

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-FR'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# Name of the directory to collect static files into. python manage.py collectstatic
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Tailles maximales
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5 MB

# Debug toolbar settings
INTERNAL_IPS = [
    "127.0.0.1",
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# If use HMR or not.
DJANGO_VITE = {
    "default": {
        "dev_mode": DEBUG,
        "dev_server_host": env.str("DJANGO_VITE_DEV_SERVER_HOST", default="127.0.0.1"), # type: ignore
        "dev_server_port": env.int("DJANGO_VITE_DEV_SERVER_PORT", default=5173), # type: ignore
    }
}

# Where ViteJS assets are built.
DJANGO_VITE_ASSETS_PATH = BASE_DIR / "frontend" / "dist"
# Include DJANGO_VITE_ASSETS_PATH into STATICFILES_DIRS to be copied inside
# when run command python manage.py collectstatic
STATICFILES_DIRS = [
    DJANGO_VITE_ASSETS_PATH,
    BASE_DIR / "static"
]

INERTIA_LAYOUT = "inertia_base.html"
INERTIA_SSR_URL = inertia_settings.INERTIA_SSR_URL
INERTIA_SSR_ENABLED = inertia_settings.INERTIA_SSR_ENABLED
INERTIA_JSON_ENCODER = inertia_settings.INERTIA_JSON_ENCODER

# http://whitenoise.evans.io/en/stable/django.html#WHITENOISE_IMMUTABLE_FILE_TEST
def immutable_file_test(path, url):
    # Match vite (rollup)-generated hashes, à la, `some_file-CSliV9zW.js`
    return re.match(r"^.+[.-][0-9a-zA-Z_-]{8,12}\..+$", url)

WHITENOISE_IMMUTABLE_FILE_TEST = immutable_file_test





# ==============================================================================
# LOGGING CONFIGURATION
# ==============================================================================

LOG_LEVEL = env.str('LOG_LEVEL', default='INFO').upper() # type: ignore
LOG_FILE_PATH = env.str('LOG_FILE_PATH', default=None) # type: ignore

# Use a simple, readable formatter for development, and JSON for production.
formatter = 'simple' if DEBUG else 'json'

# Base handlers: always log to console.
handlers = ['console']

# Add file handler only if the path is specified in the environment.
if LOG_FILE_PATH:
    handlers.append('file')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {
            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
            'format': '%(asctime)s %(name)s %(levelname)s %(module)s %(funcName)s %(lineno)d %(message)s'
        },
        'simple': {
            '()': 'django.utils.log.ServerFormatter',
            'format': '[{server_time}] {levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': formatter,
            'level': LOG_LEVEL,
        },
    },
    'root': {
        'handlers': handlers,
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': handlers,
            'level': LOG_LEVEL,
            'propagate': False,
        },
        # A specific logger for our application's code.
        'app': {
            'handlers': handlers,
            'level': LOG_LEVEL,
            'propagate': False,
        },
    }
}

# Add file handler config dynamically if path is provided.
if LOG_FILE_PATH:
    LOGGING['handlers']['file'] = {
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': LOG_FILE_PATH,
        'maxBytes': 1024 * 1024 * 5,  # 5 MB
        'backupCount': 5,
        'formatter': 'json',
        'level': LOG_LEVEL,
    }
