# Generated by Django 5.2.9 on 2026-02-11 18:47

import django.contrib.postgres.search
import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emploi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre du poste')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('nom_structure', models.CharField(max_length=255, verbose_name='Nom de la structure')),
                ('description', models.TextField(verbose_name='Description HTML(rich-text)')),
                ('description_text', models.TextField(blank=True, null=True, verbose_name='Description textuelle')),
                ('type_emploi', models.CharField(blank=True, choices=[('temps_plein_terrain', 'Temps plein terrain'), ('temps_partiel_terrain', 'Temps partiel terrain'), ('temps_plein_ligne', 'Temps plein en ligne'), ('temps_partiel_ligne', 'Temps partiel en ligne'), ('freelance', 'Freelance'), ('contrat', 'Contrat')], max_length=40, null=True, verbose_name="Type d'emploi")),
                ('adresse', models.CharField(max_length=150, verbose_name='Lieu')),
                ('ville', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('pays', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Pays')),
                ('email_contact', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contact')),
                ('telephone_contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('lien_offre_original', models.URLField(blank=True, null=True, verbose_name='Lien offre originale')),
                ('lien_candidature', models.URLField(blank=True, null=True, verbose_name='Lien candidature')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('salaire_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salaire_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('active', 'Active'), ('expiree', 'Expirée'), ('pourvue', 'Pourvue'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('est_valide', models.BooleanField(default=False, verbose_name='Validé')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('commentaire_validation', models.TextField(blank=True, null=True, verbose_name='Commentaire de validation')),
            ],
            options={
                'verbose_name': 'Emploi',
                'verbose_name_plural': 'Emplois',
                'db_table': 'emploi',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre de la formation')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('nom_structure', models.CharField(max_length=255, verbose_name='Nom de la structure')),
                ('description', models.TextField(verbose_name='Description HTML (rich text)')),
                ('description_text', models.TextField(blank=True, null=True, verbose_name='Description textuelle')),
                ('type_formation', models.CharField(choices=[('en_ligne', 'En ligne'), ('presentiel', 'Présentiel'), ('hybride', 'Hybride')], max_length=20, verbose_name='Type de formation')),
                ('adresse', models.CharField(blank=True, max_length=150, null=True, verbose_name='Lieu')),
                ('ville', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('pays', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Pays')),
                ('email_contact', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contact')),
                ('telephone_contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('lien_formation', models.URLField(blank=True, null=True, verbose_name='Lien de la formation')),
                ('lien_inscription', models.URLField(blank=True, null=True, verbose_name="Lien d'inscription")),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('est_payante', models.BooleanField(default=False, verbose_name='Formation payante')),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('duree_heures', models.IntegerField(blank=True, null=True, verbose_name='Durée en heures')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('active', 'Active'), ('expiree', 'Expirée'), ('annulee', 'Annulée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('est_valide', models.BooleanField(default=False, verbose_name='Validé')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('commentaire_validation', models.TextField(blank=True, null=True, verbose_name='Commentaire de validation')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'db_table': 'formation',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre du stage')),
                ('slug', models.SlugField(blank=True, help_text='Identifiant unique pour les URLs', null=True, unique=True, verbose_name='Slug')),
                ('nom_structure', models.CharField(max_length=255, verbose_name='Nom de la structure')),
                ('description', models.TextField(verbose_name='Description HTML (rich-text)')),
                ('description_text', models.TextField(blank=True, null=True, verbose_name='Description texte')),
                ('type_stage', models.CharField(choices=[('ouvrier', 'Ouvrier'), ('academique', 'Académique'), ('professionnel', 'Professionnel')], max_length=20, verbose_name='Type de stage')),
                ('adresse', models.CharField(max_length=150, verbose_name='Lieu')),
                ('ville', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('pays', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Pays')),
                ('email_contact', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contact')),
                ('telephone_contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('lien_offre_original', models.URLField(blank=True, null=True, verbose_name='Lien offre originale')),
                ('lien_candidature', models.URLField(blank=True, null=True, verbose_name='Lien candidature')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('active', 'Active'), ('expiree', 'Expirée'), ('pourvue', 'Pourvue'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('est_valide', models.BooleanField(default=False, verbose_name='Validé')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('commentaire_validation', models.TextField(blank=True, null=True, verbose_name='Commentaire de validation')),
            ],
            options={
                'verbose_name': 'Stage',
                'verbose_name_plural': 'Stages',
                'db_table': 'stage',
                'ordering': ['-date_publication'],
            },
        ),
    ]
