# Generated by Django 5.2.9 on 2026-01-17 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_telephone_alter_user_email'),
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='devise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='core.devise', verbose_name='Devise'),
        ),
    ]
