# Generated by Django 5.2.9 on 2026-01-21 20:28

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('opportunities', '0001_initial'),
        ('organizations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploi',
            name='createur_profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois_crees', to='users.profil', verbose_name='Créateur'),
        ),
        migrations.AddField(
            model_name='emploi',
            name='devise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emplois', to='core.devise', verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='emploi',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois', to='organizations.organisation', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='emploi',
            name='validateur_profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois_valides', to='users.profil', verbose_name='Validateur'),
        ),
        migrations.AddField(
            model_name='formation',
            name='createur_profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations_creees', to='users.profil', verbose_name='Créateur'),
        ),
        migrations.AddField(
            model_name='formation',
            name='devise',
            field=models.ForeignKey(blank=True, help_text='Devise de la formation (si payante)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='core.devise', verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='formation',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='organizations.organisation', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='formation',
            name='validateur_profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations_validees', to='users.profil', verbose_name='Validateur'),
        ),
        migrations.AddField(
            model_name='stage',
            name='createur_profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages_crees', to='users.profil', verbose_name='Créateur'),
        ),
        migrations.AddField(
            model_name='stage',
            name='domaines',
            field=models.ManyToManyField(related_name='stages', to='core.domaine', verbose_name='Domaine'),
        ),
        migrations.AddField(
            model_name='stage',
            name='filieres',
            field=models.ManyToManyField(related_name='stages', to='core.filiere', verbose_name='Filière'),
        ),
        migrations.AddField(
            model_name='stage',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages', to='organizations.organisation', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='stage',
            name='secteurs',
            field=models.ManyToManyField(related_name='stages', to='core.secteuractivite', verbose_name='Secteur'),
        ),
        migrations.AddField(
            model_name='stage',
            name='validateur_profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages_valides', to='users.profil', verbose_name='Validateur'),
        ),
        migrations.AddIndex(
            model_name='emploi',
            index=models.Index(fields=['statut', 'est_valide'], name='emploi_statut_est_valide'),
        ),
        migrations.AddIndex(
            model_name='emploi',
            index=models.Index(fields=['date_publication'], name='emploi_date_publication'),
        ),
        migrations.AddIndex(
            model_name='stage',
            index=models.Index(fields=['statut', '-date_publication'], name='stage_statut_bdca8a_idx'),
        ),
        migrations.AddIndex(
            model_name='stage',
            index=models.Index(fields=['ville', 'pays'], name='stage_ville_687a66_idx'),
        ),
        migrations.AddIndex(
            model_name='stage',
            index=models.Index(fields=['type_stage', 'statut'], name='stage_type_st_293490_idx'),
        ),
        migrations.AddIndex(
            model_name='stage',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='stage_search__f88252_gin'),
        ),
    ]
