# Generated by Django 5.2.9 on 2026-02-21 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stage',
            new_name='opportuniti_statut_096ef9_idx',
            old_name='stage_statut_bdca8a_idx',
        ),
        migrations.RenameIndex(
            model_name='stage',
            new_name='opportuniti_ville_623e8e_idx',
            old_name='stage_ville_687a66_idx',
        ),
        migrations.RenameIndex(
            model_name='stage',
            new_name='opportuniti_type_st_b6f239_idx',
            old_name='stage_type_st_293490_idx',
        ),
        migrations.RenameIndex(
            model_name='stage',
            new_name='opportuniti_search__9e0a7a_gin',
            old_name='stage_search__f88252_gin',
        ),
        migrations.AlterModelTable(
            name='emploi',
            table='opportunities_emplois',
        ),
        migrations.AlterModelTable(
            name='formation',
            table='opportunities_formations',
        ),
        migrations.AlterModelTable(
            name='stage',
            table='opportunities_stages',
        ),
    ]
