# Generated by Django 5.2.9 on 2026-01-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_telephone_alter_user_email'),
        ('opportunities', '0003_alter_formation_devise'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='domaine',
            field=models.ManyToManyField(related_name='stages', to='core.domaine', verbose_name='Domaine'),
        ),
        migrations.AddField(
            model_name='stage',
            name='filiere',
            field=models.ManyToManyField(related_name='stages', to='core.filiere', verbose_name='Filière'),
        ),
        migrations.AddField(
            model_name='stage',
            name='secteur',
            field=models.ManyToManyField(related_name='stages', to='core.secteuractivite', verbose_name='Secteur'),
        ),
    ]
