# Generated by Django 5.2.9 on 2026-01-19 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_stage_domaine_stage_filiere_stage_secteur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage',
            old_name='domaine',
            new_name='domaines',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='filiere',
            new_name='filieres',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='secteur',
            new_name='secteurs',
        ),
    ]
